import re
from typing import Any, Dict, Union
import sys
import importlib
import inspect
import os
from dotenv import dotenv_values, load_dotenv
from pathlib import Path
from typing import TYPE_CHECKING
from byper.__core__.constants import REQUIREMENTS_FILE
from byper.__core__.project_env import find_project_root, get_project_site_packages
from types import ModuleType

if TYPE_CHECKING:
    from byper.__core__.manifest import Manifest

Manifest = getattr(importlib.import_module("byper.__core__.manifest"), "Manifest")


def is_vcs_url(package: str) -> bool:
    vcs_prefixes = ("git+", "hg+", "svn+", "bzr+")
    if package.startswith(vcs_prefixes):
        return True
    # also treat plain git/http URLs as VCS-like
    return bool(re.match(r"^(?:https?|git)://", package))

def generate_tasks_stub():
    base_path = find_project_root()
    path = get_project_site_packages(base_path) / "byper" / "tasks"

    stub_path = path / "__init__.pyi"
    manifest = Manifest.load_requirements_manifest()
    tasks = manifest.get("tasks", {})

    lines = [
        f"def {task_name}() -> None: ..."
        for task_name in tasks
        if task_name.isidentifier()
    ]

    content = "\n".join(lines) + "\n"
    path.mkdir(parents=True, exist_ok=True)

    try:
        with open(stub_path, "w") as f:
            f.write(content)
    except Exception as e:
        # Optional: silently ignore or log error
        print(f"[Warning] Failed to write stub file: {e}")


def load_env_file(file_path: Union[str, Path]) -> Dict[str, str]:
    """Loads a .env file using python-dotenv and returns key-value pairs."""
    path = Path(file_path).resolve()

    # Load into os.environ (side-effect)
    load_dotenv(dotenv_path=path, override=True)

    # Return dict (for __init__.pyi generation)
    return {k: str(v) for k, v in dotenv_values(path).items() if k}


def load_env_from_manifest() -> Dict[str, Any]:
    """Loads env variables from requirements.yaml, supports 'from_file' and inline overrides."""
    data: Dict[str, Any] = {}
    manifest = Manifest.load_requirements_manifest()
    env_config = manifest.get("env", {})

    if not isinstance(env_config, dict):
        return data

    # 1. Load from `from_file` first
    file_key = env_config.get("from_file")
    if isinstance(file_key, str):
        root = find_project_root()
        file_path = root / file_key
        if not file_path.is_file():
            file_path = Path(file_key).resolve()
        if file_path.is_file():
            file_data = load_env_file(file_path)
            data.update(file_data)  # Add all .env values

    # 2. Load inline values (override file)
    for key, value in env_config.items():
        if key == "from_file":
            continue  # already handled

        os.environ[key] = str(value)
        data[key] = str(value)

    return data


def generate_env_stub():
    """Generates a __init__.pyi stub file with env variables."""
    lines = [
        "# Auto-generated by Byper for IDE support",
        "from typing import Any",
        "",
    ]
    env_data = load_env_from_manifest()
    for key in sorted(env_data):
        if key.isidentifier():
            lines.append(f"{key}: Any")

        else:
            lines.append(f"# Invalid Python identifier: {key}")

    base_path = find_project_root()
    path = get_project_site_packages(base_path) / "byper" / "env"
    pyi_path = path / "__init__.pyi"

    path.mkdir(parents=True, exist_ok=True)

    with open(pyi_path, "w") as f:
        f.write("\n".join(lines))
