from typing import Callable, Awaitable as TypingAwaitable, TypeVar, ParamSpec, Any

P = ParamSpec("P")
R = TypeVar("R")


class AwaiterModule:
    def next(self, fn: Callable[[Any], Any]) -> "AwaiterModule": ...
    def error(self, fn: Callable[[Exception], Any]) -> "AwaiterModule": ...
    def always(self, fn: Callable[[], None]) -> "AwaiterModule": ...
    def __await__(self) -> TypingAwaitable[Any]: ...


class AwaitableDecorator:
    def __call__(self, func: Callable[P, TypingAwaitable[R]]) -> Callable[P, AwaiterModule]: ...


class __Awaiter__:
    def wait(self, delay: float = 0) -> AwaitableDecorator: ...
    def all(self, awaitables: list[TypingAwaitable[Any]]) -> AwaiterModule: ...
    def done(self, awaitable: TypingAwaitable[Any]) -> AwaiterModule: ...
    def error(self, error: Exception) -> AwaiterModule: ...



